name: Node.js CI (Yarn)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Lint code
      run: yarn lint
      
    - name: Run tests with coverage
      run: yarn test:coverage
      
    - name: Upload coverage reports as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report-${{ github.event_name }}-${{ github.run_number }}
        path: coverage/
        retention-days: 30
        
    - name: Display coverage summary
      run: |
        echo " Code Coverage Summary:"
        echo "=========================="
        cat coverage/lcov.info | head -20 || echo "Coverage file not found"
        echo ""
        echo " Coverage artifacts uploaded and available for 30 days"
        
    - name: PR Quality Gate
      if: github.event_name == 'pull_request'
      run: |
        echo " Pull Request Quality Checks:"
        echo " Linting passed"
        echo " Tests passed"
        echo " Code coverage meets threshold (100%)"
        echo " PR is ready for review and merge!"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./